# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 578dbe21d94bcafc934673738bdd3c72da30ea2d8e3dcfed31b76ebc0495c4dca41971a3ee2a08eaab90fc77155dbb69b5bf6c7d8a2769fca3af2a6fc76c3969

test:
  secret_key_base: 1e00ef2759b49c5252f12accacfbeb5c304895ca101b983cf188931adb134c09c33862b4eb81f6446dc6f71ad73747fddc91f061448890b77261a964bae888dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
